name: Build Swagger UI
on:
  push:
    branches: ['master']
    paths-ignore:
        - '**/swagger.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: npm install -g insomnia-inso
    - run: npm install -g @apidevtools/swagger-cli
    - name: Generate Swagger Yaml
      run: inso export spec ${{ secrets.SPEC_INFO }} --output output.yaml --ci
    - name: Generate Swagger JSON From Yaml
      run: swagger-cli bundle --outfile swagger.json output.yaml
    - name: Delete Output Yaml
      run: rm -rf output.yaml
    - name: Push Generator to Branch
      run: |
        git config --global user.name "${{ secrets.GIT_DEPLOY_NAME }}"
        git config --global user.email "${{ secrets.GIT_DEPLOY_EMAIL }}"
        echo "Push New Change Swagger.json"
        git add swagger.json
        git commit -m "Update Swagger JSON"
        git push
