name: Build Swagger UI
on:
  push:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: yarn global add insomnia-inso
    - run: yarn global add @apidevtools/swagger-cli
    - name: Generate Swagger Yaml
      run: inso export spec ${{ secrets.SPEC_INFO }}
    - name: Generate Swagger JSON From Yaml
      run: swagger-cli bundel -o swagger.json -f json output.yml
    - name: Push Generator to Branch
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@users.noreply.github.com"
        git add swagger.json
        git commit -m "Update Swagger JSON"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}